title: Labs
description: 👨‍🏫 Courses and projects
baseurl: "/"
url: "https://khannurien.github.io"

heading_anchors: true

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
